package com.aira.api.market.domain;

public enum AuthorityScopeType {
    COMPANY_REPORTED_RESULTS,
    COMPANY_OFFICIAL_STATEMENT,
    REGULATORY_DISCLOSURE,
    LISTING_STATUS,
    MARKET_TRADING_DATA,
    MONETARY_POLICY_DECISION,
    OFFICIAL_ECONOMIC_STATISTICS
}
