import { expect, test } from '@playwright/test'

// Opt-in: run only against an isolated test database. This creates a synthetic user.
test('real backend finance lifecycle preserves account and deletes only finance data', async ({ page }) => {
  test.skip(process.env.AIRA_FINANCE_LIVE_E2E !== 'true', 'Requires an isolated API/database')
  const nickname = 'PFL' + Date.now()
  const password = 'FinanceBrowserTest42!'
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/finance')
  await page.getByRole('button', { name: '회원가입', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('닉네임').fill(nickname)
  await dialog.locator('#password').fill(password)
  await dialog.getByRole('button', { name: '회원가입', exact: true }).click()
  await expect(dialog.getByText(/회원가입이 완료됐습니다/)).toBeVisible()
  await dialog.locator('#password').fill(password)
  await dialog.getByRole('button', { name: '로그인', exact: true }).click()
  await expect(page.getByRole('heading', { name: /내 금융을 열기 전/ })).toBeVisible()
  await page.getByLabel('AIRA 비밀번호').fill(password)
  await page.getByRole('button', { name: '내 금융 열기' }).click()
  await page.getByRole('button', { name: '데모 데이터 연결', exact: true }).click()
  await expect(page.locator('.finance-total-value')).toHaveText('1,375,000원')
  await expect(page.locator('.finance-notice')).toContainText('실제 금융기관 연결이 아닙니다')
  await page.getByLabel('전체 예산 설정').fill('2000000')
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await expect(page.locator('.finance-total-context')).toContainText('남은 예산 625,000원')
  await page.reload()
  await expect(page.locator('.finance-total-context')).toContainText('남은 예산 625,000원')
  await page.getByRole('button', { name: '데모 연결 동의 해제' }).click()
  await expect(page.locator('.finance-notice')).toContainText('자동 삭제되지 않습니다')
  await expect(page.locator('.finance-total-value')).toHaveText('1,375,000원')
  await page.getByRole('button', { name: '금융데이터 관리' }).click()
  await page.getByRole('button', { name: '취소', exact: true }).click()
  await expect(page.locator('.finance-total-value')).toHaveText('1,375,000원')
  await page.getByRole('button', { name: '금융데이터 관리' }).click()
  await page.getByRole('button', { name: '금융데이터 전체 삭제' }).click()
  await expect(page.getByRole('heading', { name: /내 금융을 열기 전/ })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: /내 금융을 열기 전/ })).toBeVisible()
  await page.getByLabel('AIRA 비밀번호').fill(password)
  await page.getByRole('button', { name: '내 금융 열기' }).click()
  await expect(page.locator('.finance-total-value')).toHaveText('0원')
  await expect(page.locator('.finance-total-context')).toContainText('아직 설정 안 됨')
  await expect(page.getByRole('button', { name: '데모 데이터 연결', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '로그아웃', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '내 금융 잠그기' }).click()
  await expect(page.getByRole('heading', { name: /내 금융을 열기 전/ })).toBeVisible()
  await page.getByRole('button', { name: '로그아웃', exact: true }).click()
  expect(errors).toEqual([])
})
